### ISSUE TITLE
0.5.3 fails to build on rustc 1.34.2 (Debian stable)

### ISSUE THREAD

**Issue by victorjulien** [XAMPPRocky/remove_dir_all#20]
Hi, at https://github.com/OISF/suricata we're getting CI failures because we test on Debian stable, which has rustc 1.34.2. The error rust gives is:
```
 Compiling remove_dir_all v0.5.3
error[E0658]: `cfg(doctest)` is experimental and subject to change
  --> /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/remove_dir_all-0.5.3/src/lib.rs:12:7
  |
  | #[cfg(doctest)]
  |       ^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/62210

error[E0658]: `cfg(doctest)` is experimental and subject to change
  --> /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/remove_dir_all-0.5.3/src/lib.rs:16:7
 |
 | #[cfg(doctest)]
 |       ^^^^^^^
 |
 = note: for more information, see https://github.com/rust-lang/rust/issues/62210

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `remove_dir_all`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cbindgen v0.14.1`, intermediate artifacts can be found at `/tmp/cargo-installsPJmJE`
```

For us `remove_dir_all` is a rather indirect dependency.We use `cbindgen`:
```
$ cargo tree
cbindgen v0.14.2 (/home/victor/sync/devel/3rdparty/cbindgen)
...
├── tempfile v3.1.0
│   ├── cfg-if v0.1.10
│   ├── libc v0.2.71
│   ├── rand v0.7.3
│   │   ├── getrandom v0.1.14
│   │   │   ├── cfg-if v0.1.10
│   │   │   └── libc v0.2.71
│   │   ├── libc v0.2.71
│   │   ├── rand_chacha v0.2.2
│   │   │   ├── ppv-lite86 v0.2.8
│   │   │   └── rand_core v0.5.1
│   │   │       └── getrandom v0.1.14 (*)
│   │   └── rand_core v0.5.1 (*)
│   └── remove_dir_all v0.5.3
└── toml v0.5.6
    └── serde v1.0.112 (*)
```

The reason we care about Debian stable's rustc version is that Suricata is packaged by Debian and we would like to make sure it can continue to be.

Thanks!

**Comment by XAMPPRocky** [comment]
@victorjulien Thank you for your issue! However, I'm only interested in supporting the latest version of the compiler. If you'd like to use a version that is compatible with with `1.34.2` you can use. continue to use `0.5.2`. If you have specific compiler version requirements for your project I would recommend committing your `Cargo.lock` to avoid this issue.
